# Generated by Django 2.1.5 on 2019-02-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name='留言内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-create_time'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='friend',
            options={'ordering': ['create_time'], 'verbose_name': '友链', 'verbose_name_plural': '友链'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['create_time'], 'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ['create_time'], 'verbose_name': '网站', 'verbose_name_plural': '网站'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(unique=True, verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articles', related_query_name='article', to='blog.Tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=20, unique=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='url',
            field=models.URLField(unique=True, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=10, unique=True, verbose_name='标签名'),
        ),
        migrations.AlterField(
            model_name='website',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='website',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(unique=True, verbose_name='链接'),
        ),
    ]
