# Generated by Django 2.1.5 on 2019-02-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190201_0735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={'ordering': ['-create_time'], 'verbose_name': '友链', 'verbose_name_plural': '友链'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-create_time'], 'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ['-create_time'], 'verbose_name': '网站', 'verbose_name_plural': '网站'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='client_ip',
            field=models.CharField(max_length=150, null=True, verbose_name='IP'),
        ),
    ]
